spring:

  main:
    allow-bean-definition-overriding: true

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 10

    hibernate:
      ddl-auto: create

    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    generate-ddl: true

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    hikari:
      batch:
        jdbc-url: jdbc:h2:mem:testdb;INIT=CREATE SCHEMA IF NOT EXISTS EX_BATCH
        username: sa
        password:
        driver-class-name: org.h2.Driver

      member:
        jdbc-url: jdbc:h2:mem:testdb;INIT=CREATE SCHEMA IF NOT EXISTS EX_MEMBER
        username: sa
        password:
        driver-class-name: org.h2.Driver

      board:
        jdbc-url: jdbc:h2:mem:testdb;INIT=CREATE SCHEMA IF NOT EXISTS EX_BOARD
        username: sa
        password:
        driver-class-name: org.h2.Driver

logging:
  level:
    org:
      springframework:
        batch: debug